### ISSUE TITLE
Błędy

### ISSUE THREAD

**Issue by DjHack0001** [DawidStankiewicz/LibPLUS#2]
Cześć. W moim przypadku w ogóle inne błędy wychodzą.
http://imgur.com/a/gmVHZ

Tam gdzie jest 4-2.50 jest 4- z wagą 3
W miejscu 12.05 jest 1 z wagą 1
A w pozycji 12.00  jest 1 z wagą 3

Myślę, że uda się rozwiązać :)
Pozdrawiam.

**Comment by Szczypioreg** [comment]
@DjHack0001 dziękuje za zgłoszenie. Mógłbyś wysłać fragment kodu HTML ocenami w nawiasach i następną oceną w której znajduje się średnia?
